#!/usr/bin/env python3
"""Round Coordinator - Manages the debate flow through rounds"""

from typing import List, Dict, Any, Optional
from dataclasses import dataclass

from ..agent_architecture_core import (
    RoundType, DiscussionContext, AgentOpinion, DebateMessage, 
    MarketContext, MessageType, SignalType, DiscussingAgent
)
from .conflict_detector import ConflictDetector


@dataclass
class RoundResult:
    """Results after completing a round."""
    round_type: RoundType
    messages: List[DebateMessage]
    opinions: Dict[str, AgentOpinion]
    conflicts: List[Dict[str, Any]]
    completed: bool = True


class RoundCoordinator:
    """
    Orchestrates the multi-round debate process.
    """
    
    def __init__(
        self, 
        agents: Dict[str, 'DiscussingAgent'],
        conflict_detector: Optional[ConflictDetector] = None
    ):
        self.agents = agents
        self.conflict_detector = conflict_detector or ConflictDetector()
        self.message_counter = 0
    
    def _next_message_id(self) -> str:
        self.message_counter += 1
        return f"msg_{self.message_counter:04d}"
    
    def run_round_0_independent(
        self, 
        market_context: MarketContext
    ) -> RoundResult:
        """Round 0: Each agent analyzes independently without seeing others."""
        opinions = {}
        
        # Build context with empty discussion state
        for name, agent in self.agents.items():
            context = DiscussionContext(
                market_context=market_context,
                current_round=RoundType.INDEPENDENT_ANALYSIS,
                my_previous_opinion=None,
                messages_addressed_to_me=[],
                other_agents_latest_opinions={},
                unresolved_conflicts=[],
                token_budget=2000,
            )
            
            opinion = agent.analyze_independent(context)
            opinion.agent_name = name  # Ensure name is set
            opinions[name] = opinion
        
        # Detect initial conflicts
        conflicts = self.conflict_detector.detect_conflicts(opinions)
        
        return RoundResult(
            round_type=RoundType.INDEPENDENT_ANALYSIS,
            messages=[],  # No messages in round 0
            opinions=opinions,
            conflicts=conflicts,
        )
    
    def run_round_1_critique(
        self,
        market_context: MarketContext,
        round_0_opinions: Dict[str, AgentOpinion],
    ) -> RoundResult:
        """Round 1: Agents critique each other based on round 0 opinions."""
        all_messages = []
        conflicts = self.conflict_detector.detect_conflicts(round_0_opinions)
        
        for name, agent in self.agents.items():
            my_opinion = round_0_opinions[name]
            
            # Build messages addressed to this agent
            # (In round 1, these will be generated by other agents)
            # For now, we collect all critiques from all agents
            
            context = DiscussionContext(
                market_context=market_context,
                current_round=RoundType.CRITIQUE_EXCHANGE,
                my_previous_opinion=my_opinion,
                messages_addressed_to_me=[],  # Will be populated after collection
                other_agents_latest_opinions={
                    n: o for n, o in round_0_opinions.items() if n != name
                },
                unresolved_conflicts=conflicts,
                token_budget=1500,
            )
            
            # Agent generates critiques
            messages = agent.critique_others(context)
            
            # Tag messages with IDs and metadata
            for msg in messages:
                msg.message_id = self._next_message_id()
                msg.sender = name
                msg.round_number = 1
                if msg.target:
                    # Find if target agent's opinion is in round_0_opinions
                    pass
            
            all_messages.extend(messages)
        
        # Now redistribute: each agent sees messages addressed to them
        # (Simplified: all messages are broadcast)
        return RoundResult(
            round_type=RoundType.CRITIQUE_EXCHANGE,
            messages=all_messages,
            opinions=round_0_opinions,  # Opinions don't change in round 1
            conflicts=conflicts,
        )
    
    def run_round_2_revision(
        self,
        market_context: MarketContext,
        round_0_opinions: Dict[str, AgentOpinion],
        round_1_messages: List[DebateMessage],
    ) -> RoundResult:
        """Round 2: Agents revise opinions based on critiques."""
        new_opinions = {}
        conflicts = self.conflict_detector.detect_conflicts(round_0_opinions)
        
        for name, agent in self.agents.items():
            my_opinion = round_0_opinions[name]
            
            # Filter messages addressed to this agent (or broadcast)
            my_messages = [
                m for m in round_1_messages 
                if m.target is None or m.target == name
            ]
            
            context = DiscussionContext(
                market_context=market_context,
                current_round=RoundType.OPINION_REVISION,
                my_previous_opinion=my_opinion,
                messages_addressed_to_me=my_messages,
                other_agents_latest_opinions={
                    n: o for n, o in round_0_opinions.items() if n != name
                },
                unresolved_conflicts=conflicts,
                token_budget=2000,
            )
            
            revised = agent.revise_opinion(context)
            revised.agent_name = name
            revised.changed_from_previous = (
                revised.signal != my_opinion.signal or 
                abs(revised.confidence - my_opinion.confidence) > 0.1
            )
            if revised.changed_from_previous:
                revised.change_reason = "Revised after peer critique"
            
            new_opinions[name] = revised
        
        # Detect conflicts after revision
        new_conflicts = self.conflict_detector.detect_conflicts(new_opinions)
        
        return RoundResult(
            round_type=RoundType.OPINION_REVISION,
            messages=[],  # Revision messages could be added as FINAL_STATEMENT
            opinions=new_opinions,
            conflicts=new_conflicts,
        )
    
    def get_final_opinions(self, round_2_result: RoundResult) -> Dict[str, AgentOpinion]:
        """Get final opinions after all rounds."""
        return round_2_result.opinions